# Generated by Django 4.1.7 on 2023-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(default=dict)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('url_to_image', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('content', models.CharField(max_length=300)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'NewsArticles',
            },
        ),
    ]
