# Generated by Django 4.1.7 on 2023-04-11 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='saved',
            field=models.ManyToManyField(related_name='Saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='likes',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='comments',
            field=models.ManyToManyField(related_name='Comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
