# Generated by Django 4.1.7 on 2023-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('news', '0002_newsarticle_saved_remove_newsarticle_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='comments',
            field=models.ManyToManyField(related_name='Comments', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='Likes', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='saved',
            field=models.ManyToManyField(related_name='Saved', to='user.profile'),
        ),
    ]
