# Generated by Django 4.1.7 on 2023-04-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsarticle_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='comments',
        ),
    ]
