# Generated by Django 4.1.7 on 2023-04-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('categories', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['user__user__date_joined', 'user__user__last_login'],
            },
        ),
    ]
