news_categories = [
    "general",
    "buisness",
    "technology",
    "sports",
    "entertainment",
    "health",
    "science",
]

news_sources = [
    "Associated Press",
    "BBC News",
    "CNN",
    "Reuters",
    "New York Magazine",
    "The Washington Post",
    "Fox News",
    "Al Jazeera English",
    "The Times of India",
    "ESPN",
    "Business Insider",
    "Bloomberg",
    "TechCrunch",
    "National Geographic",
    "IGN",
    "The Verge",
    "MTV News",
    "USA Today",
    "CBS News",
]
