news_categories = [
    "Business",
    "Entertainment",
    "General",
    "Health",
    "Science",
    "Sports",
    "Technology",
    "Automotive",
    "Politics",
    "Education",
    "Environment",
    "Food",
    "Gaming",
    "Music",
    "Real Estate",
    "Travel",
    "Style",
    "Books",
    "Art",
    "Film",
]

news_sources = [
    "Associated Press",
    "BBC News",
    "CNN",
    "Reuters",
    "The New York Times",
    "The Washington Post",
    "Fox News",
    "Al Jazeera English",
    "The Guardian",
    "The Times of India",
    "ESPN",
    "Business Insider",
    "Bloomberg",
    "TechCrunch",
    "National Geographic",
    "IGN",
    "The Verge",
    "MTV News",
    "USA Today",
    "CBS News",
]
